-- MOR initial catalogue and offline-order schema.
-- Apply this migration to a fresh Supabase project before connecting the app.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  role text not null default 'staff' check (role in ('admin', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.email)
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create trigger profiles_set_updated_at
  before update on public.profiles
  for each row execute procedure public.set_updated_at();

create table public.categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger categories_set_updated_at
  before update on public.categories
  for each row execute procedure public.set_updated_at();

create table public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text not null default '',
  price_minor integer not null check (price_minor >= 0),
  currency text not null default 'USD' check (char_length(currency) = 3),
  gender text not null default 'unisex' check (gender in ('men', 'women', 'unisex')),
  category_id bigint references public.categories(id) on delete set null,
  stock_quantity integer not null default 0 check (stock_quantity >= 0),
  sizes text[] not null default '{}',
  featured boolean not null default false,
  active boolean not null default true,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index products_category_id_idx on public.products(category_id);
create index products_gender_idx on public.products(gender);
create index products_active_featured_idx on public.products(active, featured);

create trigger products_set_updated_at
  before update on public.products
  for each row execute procedure public.set_updated_at();

create table public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text not null,
  alt_text text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create index product_images_product_id_idx on public.product_images(product_id, sort_order);

create or replace function public.make_order_number()
returns text
language sql
volatile
as $$
  select 'MOR-' || to_char(clock_timestamp(), 'YYYYMMDD') || '-' ||
    upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 6));
$$;

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default public.make_order_number(),
  source text not null default 'website'
    check (source in ('website', 'whatsapp', 'phone', 'instagram', 'walk_in', 'other')),
  customer_name text not null,
  customer_phone text not null,
  customer_email text,
  delivery_type text not null default 'delivery'
    check (delivery_type in ('delivery', 'pickup')),
  delivery_address text,
  delivery_notes text,
  order_status text not null default 'pending'
    check (order_status in ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')),
  delivery_status text not null default 'awaiting_assignment'
    check (delivery_status in ('not_required', 'awaiting_assignment', 'assigned', 'out_for_delivery', 'delivered', 'failed', 'returned')),
  cash_status text not null default 'cash_outstanding'
    check (cash_status in ('cash_outstanding', 'cash_collected', 'partially_collected')),
  inventory_status text not null default 'not_reserved'
    check (inventory_status in ('not_reserved', 'reserved', 'consumed', 'released')),
  inventory_reserved_at timestamptz,
  inventory_released_at timestamptz,
  subtotal_minor integer not null default 0 check (subtotal_minor >= 0),
  delivery_fee_minor integer not null default 0 check (delivery_fee_minor >= 0),
  total_minor integer not null default 0 check (total_minor >= 0),
  currency text not null default 'USD' check (char_length(currency) = 3),
  admin_notes text,
  created_by uuid references public.profiles(id) on delete set null,
  confirmed_at timestamptz,
  completed_at timestamptz,
  cancelled_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (delivery_type = 'delivery' and nullif(trim(delivery_address), '') is not null)
    or delivery_type = 'pickup'
  )
);

create index orders_created_at_idx on public.orders(created_at desc);
create index orders_status_idx on public.orders(order_status, delivery_status, cash_status);
create index orders_customer_phone_idx on public.orders(customer_phone);

create trigger orders_set_updated_at
  before update on public.orders
  for each row execute procedure public.set_updated_at();

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name_snapshot text not null,
  size text not null default '',
  quantity integer not null check (quantity > 0),
  unit_price_minor integer not null check (unit_price_minor >= 0),
  line_total_minor integer not null check (line_total_minor >= 0),
  created_at timestamptz not null default now()
);

create index order_items_order_id_idx on public.order_items(order_id);
create index order_items_product_id_idx on public.order_items(product_id);

create table public.order_status_history (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  changed_by uuid references public.profiles(id) on delete set null,
  field_name text not null check (field_name in ('order_status', 'delivery_status', 'cash_status')),
  old_value text,
  new_value text not null,
  note text,
  created_at timestamptz not null default now()
);

create index order_status_history_order_id_idx on public.order_status_history(order_id, created_at desc);

-- RLS: public users can read only active catalogue records. Admin users can manage data.
alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;

create policy profiles_self_read
  on public.profiles for select
  to authenticated
  using (id = auth.uid() or public.is_admin());

create policy profiles_admin_update
  on public.profiles for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy categories_public_read
  on public.categories for select
  to anon, authenticated
  using (active = true or public.is_admin());

create policy categories_admin_insert
  on public.categories for insert
  to authenticated
  with check (public.is_admin());

create policy categories_admin_update
  on public.categories for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy categories_admin_delete
  on public.categories for delete
  to authenticated
  using (public.is_admin());

create policy products_public_read
  on public.products for select
  to anon, authenticated
  using (active = true or public.is_admin());

create policy products_admin_insert
  on public.products for insert
  to authenticated
  with check (public.is_admin());

create policy products_admin_update
  on public.products for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy products_admin_delete
  on public.products for delete
  to authenticated
  using (public.is_admin());

create policy product_images_public_read
  on public.product_images for select
  to anon, authenticated
  using (
    public.is_admin()
    or exists (
      select 1 from public.products
      where products.id = product_images.product_id and products.active = true
    )
  );

create policy product_images_admin_insert
  on public.product_images for insert
  to authenticated
  with check (public.is_admin());

create policy product_images_admin_update
  on public.product_images for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy product_images_admin_delete
  on public.product_images for delete
  to authenticated
  using (public.is_admin());

create policy orders_admin_read
  on public.orders for select
  to authenticated
  using (public.is_admin());

create policy orders_admin_insert
  on public.orders for insert
  to authenticated
  with check (public.is_admin());

create policy orders_admin_update
  on public.orders for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy orders_admin_delete
  on public.orders for delete
  to authenticated
  using (public.is_admin());

create policy order_items_admin_read
  on public.order_items for select
  to authenticated
  using (public.is_admin());

create policy order_items_admin_insert
  on public.order_items for insert
  to authenticated
  with check (public.is_admin());

create policy order_items_admin_update
  on public.order_items for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy order_items_admin_delete
  on public.order_items for delete
  to authenticated
  using (public.is_admin());

create policy order_status_history_admin_read
  on public.order_status_history for select
  to authenticated
  using (public.is_admin());

create policy order_status_history_admin_insert
  on public.order_status_history for insert
  to authenticated
  with check (public.is_admin());

-- The order function is called by the Edge Function with a server-only key.
-- It validates current prices and stock before writing an order and snapshots each line.
create or replace function public.create_order(
  p_source text,
  p_customer_name text,
  p_customer_phone text,
  p_customer_email text,
  p_delivery_type text,
  p_delivery_address text,
  p_delivery_notes text,
  p_items jsonb,
  p_created_by uuid default null
)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  v_order_id uuid;
  v_order_number text;
  v_currency text;
  v_subtotal integer := 0;
  v_item jsonb;
  v_product public.products%rowtype;
  v_product_id bigint;
  v_size text;
  v_quantity integer;
  v_line_total integer;
begin
  if nullif(trim(p_customer_name), '') is null then
    raise exception using message = 'Customer name is required', errcode = '22023';
  end if;

  if nullif(trim(p_customer_phone), '') is null then
    raise exception using message = 'Customer phone is required', errcode = '22023';
  end if;

  if p_source not in ('website', 'whatsapp', 'phone', 'instagram', 'walk_in', 'other') then
    raise exception using message = 'Invalid order source', errcode = '22023';
  end if;

  if p_delivery_type not in ('delivery', 'pickup') then
    raise exception using message = 'Invalid delivery type', errcode = '22023';
  end if;

  if p_delivery_type = 'delivery' and nullif(trim(p_delivery_address), '') is null then
    raise exception using message = 'Delivery address is required', errcode = '22023';
  end if;

  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception using message = 'At least one order item is required', errcode = '22023';
  end if;

  insert into public.orders (
    source,
    customer_name,
    customer_phone,
    customer_email,
    delivery_type,
    delivery_address,
    delivery_notes,
    delivery_status,
    created_by
  )
  values (
    p_source,
    trim(p_customer_name),
    trim(p_customer_phone),
    nullif(trim(p_customer_email), ''),
    p_delivery_type,
    case when p_delivery_type = 'delivery' then trim(p_delivery_address) else null end,
    nullif(trim(p_delivery_notes), ''),
    case when p_delivery_type = 'pickup' then 'not_required' else 'awaiting_assignment' end,
    p_created_by
  )
  returning id, order_number into v_order_id, v_order_number;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := (v_item ->> 'product_id')::bigint;
    v_size := coalesce(trim(v_item ->> 'size'), '');
    v_quantity := (v_item ->> 'quantity')::integer;

    if v_quantity is null or v_quantity < 1 then
      raise exception using message = 'Order quantities must be positive', errcode = '22023';
    end if;

    select * into v_product
    from public.products
    where id = v_product_id and active = true
    for update;

    if not found then
      raise exception using message = 'A selected product is unavailable', errcode = '22023';
    end if;

    if v_product.stock_quantity < v_quantity then
      raise exception using message = 'A selected product does not have enough stock', errcode = '22023';
    end if;

    if cardinality(v_product.sizes) > 0 and not (v_size = any(v_product.sizes)) then
      raise exception using message = 'A selected size is unavailable', errcode = '22023';
    end if;

    if v_currency is null then
      v_currency := v_product.currency;
    elsif v_currency <> v_product.currency then
      raise exception using message = 'Products must use one currency', errcode = '22023';
    end if;

    v_line_total := v_product.price_minor * v_quantity;
    v_subtotal := v_subtotal + v_line_total;

    insert into public.order_items (
      order_id,
      product_id,
      product_name_snapshot,
      size,
      quantity,
      unit_price_minor,
      line_total_minor
    )
    values (
      v_order_id,
      v_product.id,
      v_product.name,
      v_size,
      v_quantity,
      v_product.price_minor,
      v_line_total
    );
  end loop;

  update public.orders
  set subtotal_minor = v_subtotal,
      total_minor = v_subtotal,
      currency = coalesce(v_currency, 'USD')
  where id = v_order_id;

  insert into public.order_status_history (
    order_id,
    changed_by,
    field_name,
    old_value,
    new_value,
    note
  )
  values (v_order_id, p_created_by, 'order_status', null, 'pending', 'Order created');

  return jsonb_build_object(
    'id', v_order_id,
    'order_number', v_order_number,
    'order_status', 'pending',
    'delivery_status', case when p_delivery_type = 'pickup' then 'not_required' else 'awaiting_assignment' end,
    'cash_status', 'cash_outstanding',
    'subtotal_minor', v_subtotal,
    'total_minor', v_subtotal,
    'currency', coalesce(v_currency, 'USD')
  );
end;
$$;

revoke all on function public.create_order(text, text, text, text, text, text, text, jsonb, uuid) from public, anon, authenticated;
grant execute on function public.create_order(text, text, text, text, text, text, text, jsonb, uuid) to service_role;

-- Status changes, stock reservation/release, and history are kept in one transaction.
create or replace function public.update_order_status(
  p_order_id uuid,
  p_order_status text default null,
  p_delivery_status text default null,
  p_cash_status text default null,
  p_note text default null,
  p_changed_by uuid default null
)
returns jsonb
language plpgsql
security definer set search_path = public
as $$
declare
  v_order public.orders%rowtype;
  v_item public.order_items%rowtype;
  v_product public.products%rowtype;
  v_next_order_status text;
  v_next_delivery_status text;
  v_next_cash_status text;
begin
  select * into v_order
  from public.orders
  where id = p_order_id
  for update;

  if not found then
    raise exception using message = 'Order not found', errcode = '22023';
  end if;

  if p_order_status is not null and p_order_status not in ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled') then
    raise exception using message = 'Invalid order status', errcode = '22023';
  end if;

  if p_delivery_status is not null and p_delivery_status not in ('not_required', 'awaiting_assignment', 'assigned', 'out_for_delivery', 'delivered', 'failed', 'returned') then
    raise exception using message = 'Invalid delivery status', errcode = '22023';
  end if;

  if p_cash_status is not null and p_cash_status not in ('cash_outstanding', 'cash_collected', 'partially_collected') then
    raise exception using message = 'Invalid cash status', errcode = '22023';
  end if;

  v_next_order_status := coalesce(p_order_status, v_order.order_status);
  v_next_delivery_status := coalesce(p_delivery_status, v_order.delivery_status);
  v_next_cash_status := coalesce(p_cash_status, v_order.cash_status);

  if v_order.order_status = 'completed' and v_next_order_status <> 'completed' then
    raise exception using message = 'Completed orders cannot be moved backwards', errcode = '22023';
  end if;

  if v_order.order_status = 'cancelled' and v_next_order_status <> 'cancelled' then
    raise exception using message = 'Cancelled orders cannot be reopened automatically', errcode = '22023';
  end if;

  if v_order.delivery_type = 'pickup' and v_next_delivery_status <> 'not_required' then
    raise exception using message = 'Pickup orders do not have a delivery status', errcode = '22023';
  end if;

  if v_order.inventory_status = 'not_reserved'
    and v_next_order_status in ('confirmed', 'preparing', 'ready', 'completed') then
    for v_item in
      select * from public.order_items where order_id = v_order.id
    loop
      if v_item.product_id is null then
        raise exception using message = 'An order item no longer has a product reference', errcode = '22023';
      end if;

      select * into v_product
      from public.products
      where id = v_item.product_id
      for update;

      if not found or v_product.stock_quantity < v_item.quantity then
        raise exception using message = 'There is not enough stock to confirm this order', errcode = '22023';
      end if;

      update public.products
      set stock_quantity = stock_quantity - v_item.quantity
      where id = v_item.product_id;
    end loop;

    update public.orders
    set inventory_status = case when v_next_order_status = 'completed' then 'consumed' else 'reserved' end,
        inventory_reserved_at = now()
    where id = v_order.id;
  elsif v_order.inventory_status = 'reserved' and v_next_order_status = 'cancelled' then
    for v_item in
      select * from public.order_items where order_id = v_order.id
    loop
      if v_item.product_id is not null then
        update public.products
        set stock_quantity = stock_quantity + v_item.quantity
        where id = v_item.product_id;
      end if;
    end loop;

    update public.orders
    set inventory_status = 'released',
        inventory_released_at = now()
    where id = v_order.id;
  elsif v_order.inventory_status = 'reserved' and v_next_order_status = 'completed' then
    update public.orders
    set inventory_status = 'consumed'
    where id = v_order.id;
  elsif v_order.inventory_status = 'not_reserved' and v_next_order_status = 'cancelled' then
    update public.orders
    set inventory_status = 'released',
        inventory_released_at = now()
    where id = v_order.id;
  end if;

  update public.orders
  set order_status = v_next_order_status,
      delivery_status = v_next_delivery_status,
      cash_status = v_next_cash_status,
      confirmed_at = case
        when v_next_order_status in ('confirmed', 'preparing', 'ready', 'completed') and confirmed_at is null then now()
        else confirmed_at
      end,
      completed_at = case
        when v_next_order_status = 'completed' then coalesce(completed_at, now())
        else completed_at
      end,
      cancelled_at = case
        when v_next_order_status = 'cancelled' then coalesce(cancelled_at, now())
        else cancelled_at
      end
  where id = v_order.id;

  if v_next_order_status <> v_order.order_status then
    insert into public.order_status_history (order_id, changed_by, field_name, old_value, new_value, note)
    values (v_order.id, p_changed_by, 'order_status', v_order.order_status, v_next_order_status, p_note);
  end if;

  if v_next_delivery_status <> v_order.delivery_status then
    insert into public.order_status_history (order_id, changed_by, field_name, old_value, new_value, note)
    values (v_order.id, p_changed_by, 'delivery_status', v_order.delivery_status, v_next_delivery_status, p_note);
  end if;

  if v_next_cash_status <> v_order.cash_status then
    insert into public.order_status_history (order_id, changed_by, field_name, old_value, new_value, note)
    values (v_order.id, p_changed_by, 'cash_status', v_order.cash_status, v_next_cash_status, p_note);
  end if;

  select * into v_order from public.orders where id = v_order.id;
  return jsonb_build_object('order', to_jsonb(v_order));
end;
$$;

revoke all on function public.update_order_status(uuid, text, text, text, text, uuid) from public, anon, authenticated;
grant execute on function public.update_order_status(uuid, text, text, text, text, uuid) to service_role;
